config/routes.rb
Rails.application.routes.draw do
  root to:'pages#home'
  post '/sign_in', to: 'pages#sign_in'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :users, only: [:show,:new, :create] do
resources :lists, except: [:index, :show] do  
  resources :tasks, except: [:index, :show, :new]
  end

end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    has_many :tasks, dependent: :destroy

    belongs_to :user
    validates :title,
              presence: true
              
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :list
    validates :content,
              presence:true
    delegate :user_id, to: :list
end

app/models/user.rb
class User < ApplicationRecord
    has_many :lists
    validates :login,
              presence: true,
              uniqueness: true
    validates :password,
              presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    before_action :authenticate
    def new
       user = User.find(params[:user_id])
       @list= List.new(user: user)
    end
    
    def create
        List.create(list_params)
        redirect_to user_path(params[:user_id])
    end
    def destroy
    unless List.find_by(id: params[:id])
         redirect_to user_path(params[:user_id])
         flash[:error] = "List not Found"
    end
    List.destroy(params[:id])
    redirect_to user_path(params[:user_id])
    flash[:notice] = "Successfully destroyed"
    end

    def edit
    @list=List.find_by(id: params[:id]) 
    unless @list
    redirect_to user_path(params[:user_id]) 
    end     
    end

    def update
    @list=List.find_by(id: params[:id])
    unless @list
    redirect_to user_path(params[:user_id]) 
    end 
    @list.update(title: params[:list] [:title])
    redirect_to user_path(params[:user_id]) 
    flash[:notice] = "Successfully update..."
    end

    
    private
    def list_params
        params.require(:list).permit(:title, :user_id)
    end
    
    def authenticate
    redirect_to(root_path) unless session[:current_user_id] == params[:user_id]
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def sign_in
       @user = User.find_by(login: params[:login],password: params[:password])
       if @user
        session[:current_user_id] = @user.id.to_s
        redirect_to user_path(@user.id)
       else
       redirect_to root_path
       flash[:error] = "User not exist!"
       end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :edit, :update, :destroy]
 

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

      unless @task.save
        flash[:error] = "Error! Something went wrong..."
      end
        redirect_to  user_path(params[:user_id])
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task=Task.find_by(id: params[:id])
    unless @task
    redirect_to user_path(params[:user_id]) 
    end 
    @task.update(content: params[:task] [:content])
    redirect_to user_path(params[ :user_id]) 
    flash[:notice] = "Successfully update..."
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    unless @task.destroy
        flash[:error] = "Error! Something went wrong..."
    end
        redirect_to  user_path(params[:user_id])

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.permit(:content, :list_id)
    end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
    if session[:current_user_id] == params[:id]
        @user=User.find(params[:id])
        @lists=@user.lists.includes(:tasks)
    else
        redirect_to root_path
    end
    end
    def new
     @user=User.new
    end
    def create
        @user=User.new(user_params)
     if @user.save
        session[:current_user_id] = @user.id.to_s
        redirect_to @user
        flash[:notice] = "Successfully created..."
     else
        redirect_to new_user_path
        flash[:error] = "Not created..."
     end
    end



    private
    def user_params
        params.require(:user).permit(:login, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=h flash[:error]%>
    <%=h flash[:notice]%>

    <header class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h1>Simple TODO Lists</h1>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<%= form_for @list, url: user_list_path(@list.user_id, @list.id) do |f| %>
  <%= f.label :title%>
  <%= f.text_field :title %>
  <%= f.hidden_field :user_id%>
  <%= f.submit %>
<% end %>

app/views/lists/new.html.erb
<<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
 <div class="container">
  <div class="row">

   <div class="col-md-4"></div>
      <div id="login" class="col-md-3">
         <h1>New List</h1>
         <div class="row-fluid" >
          <div class="span4 well"> 
<%= form_for @list, url: user_lists_path(@list.user_id) do |f| %>
         <fieldset>
           <div class="control-group">
            <%= f.label :title%>
            <%= f.text_field :title %>
          
            <%= f.hidden_field :user_id%>
           </div>
           <br></br>
            <div class="form-actions">
            <%= f.submit  class: "btn btn-primary" %>
            </div>
         </fieldset>
        <% end %>
        </div>
       </div>
 </div>
</div>
<div id="main" class="col-md-5"></div>

</div>
</body>
</html>

app/views/pages/home.html.erb
<<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
 <div class="container">
  <div class="row">

   <div class="col-md-4"></div>
      <div id="login" class="col-md-3">
         <h1>Sign in</h1>
         <div class="row-fluid" >
          <div class="span4 well"> 
           <%= form_tag("/sign_in", method: "post") do %>
         <fieldset>
           <div class="control-group">
            <%= label_tag(:login, "Login name") %>
            <%= text_field_tag(:login)%>
           <div class="controls">
            <%= label_tag(:password, "Password") %>
            <%= password_field_tag(:password) %>
           </div>
           </div>
           <br></br>
            <div class="form-actions">
            <%= submit_tag ("Log In"),  class: "btn btn-primary" %>
            </div>
         </fieldset>
        <% end %>
        </div>
       </div>
<p> Don't have account?</p>
<%= link_to 'Sign Up', new_user_path, class: 'btn btn-success'  %>
 </div>
</div>
<div id="main" class="col-md-5"></div>

</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_tag user_list_tasks_path(user_id, list_id) do  %>
  <div class="input-group">
    <%= text_field_tag :content, nil, class: 'input-sm form-control' %>
    <%= hidden_field_tag :list_id, list_id %>

    <span class="input-group-btn">
      <%= submit_tag 'Create Task', class: 'input-sm btn btn-success' %>
    </span>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
 <div class="container">
  <div class="row">

   <div class="col-md-4"></div>
      <div id="login" class="col-md-3">
         <h1>Editing Task</h1>
         <div class="row-fluid" >
          <div class="span4 well"> 
          <%= form_for @task, url: user_list_task_path(@task.user_id, @task.list_id, @task.id) do |f| %>
         <fieldset>
           <div class="control-group">
            <%= f.label :content%>
            <%= f.text_field :content%>

            <%= f.hidden_field :list_id%>

           </div>
           </div>
           <br></br>
            <div class="form-actions">
            <%= f.submit class: "btn btn-primary" %>
            </div>
         </fieldset>
        <% end %>
        </div>
       </div>
 </div>
</div>
<div id="main" class="col-md-5"></div>

</div>
</body>
</html>

app/views/users/new.html.erb
<<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link href="css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
 <div class="container">
  <div class="row">

   <div class="col-md-4"></div>
      <div id="login" class="col-md-3">
         <h1>Sign Up</h1>
         <div class="row-fluid" >
          <div class="span4 well"> 
         <%= form_for @user do |f| %>
         <fieldset>
           <div class="input-group">
           
            <%= f.label :login%>
           <input class="form-control" <%= f.text_field :login%>
           <br></br>
            <%= f.label :password%>
            <input class="form-control" <%= f.password_field :password %>
           </div>
           <br></br>
            <div class="form-actions">
            <%= f.submit  class: "btn btn-primary" %>
            </div>
         </fieldset>
        <% end %>
        </div>
       </div>
 </div>
</div>
<div id="main" class="col-md-5"></div>

</div>
</body>
</html>

app/views/users/show.html.erb
<main>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <section>
        <article>
          <% @lists.each do |list|%>
            <div class="panel panel-default todoListContainer">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-md-1 text-center">
                    <span class="glyphicon glyphicon-list"></span>
                  </div>

                  <div class="col-md-9">
                    <span class="project-title">
                      <%= list.title %>
                    </span>
                  </div>

                  <div class="col-md-2">
                    <div class="pull-right project-controls">
                      <%= link_to '', edit_user_list_path(@user.id,list.id), class: 'fa fa-pencil'%>
                      |
                      <%= link_to '', user_list_path(@user.id, list.id), method: :delete, class: 'fa fa-trash' %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="task-index">
                <div class="row newTaskPanel">
                  <div class="col-md-1 text-center">
                    <span class="glyphicon glyphicon-plus"></span>
                  </div>

                  <div class="col-md-11">
                    <%= render 'tasks/form', list_id: list.id, user_id: @user.id %>
                  </div>
                </div>
              </div>

              <ul class="list-group" id="tasks">
                <% list.tasks.each do |task| %>
                  <li class="list-group-item singleTask">
                    <div class="row">
                      <div class="col-md-1 text-center">
                        <span class="fa-check-square-o"></span>
                      </div>

                      <div class="col-md-9">
                        <div class="row">
                          <span class="task-title">
                            <%= task.content %>
                          </span>
                        </div>
                      </div>

                      <div class="col-md-2">
                        <section class="pull-right task-controls">
                          <%= link_to '', edit_user_list_task_path(@user.id, list.id, task.id), class: 'fa fa-pencil'%>
                          |
                          <%= link_to '', user_list_task_path(@user.id, list.id, task.id), method: :delete, class: 'fa fa-trash-o' %>
                        </section>
                      </div>
                    </div>
                  </li>
                <%end%>
              </ul>

            </div>
          <%end%>
        </article>
      </section>

      <div class="text-center">
        <%= link_to 'ADD TODO List', new_user_list_path(@user.id), class: "btn btn-primary addTodoButton" %>
      </div>

    </div>
  </div>
</main>